cask_args appdir: '/Applications'

# Tap Repo
tap 'caskroom/versions'
tap 'caskroom/cask'
tap 'caskroom/fonts'

brew 'acme'
brew 'awscli'
brew 'certbot'
brew 'git'
brew 'git-flow'
brew 'httpie'
brew 'htop'
brew 'kops'
brew 'kubectx'
brew 'kubernetes-cli'
brew 'kubernetes-helm'
brew 'mackup'
brew 'mtr'
brew 'mysql'
brew 'mysql-client'
brew 'ncdu'
brew 'siege'
brew 'stormssh'
brew 'rbenv'
brew 'tree'
brew 'tsung'
brew 'wget'
brew 'iperf'
brew 'jq'
brew 'xml2'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'

cask 'alfred'
cask 'appzapper'
cask 'google-cloud-sdk'
cask 'caffeine'
#cask 'daisydisk'
#cask 'dash'
cask 'docker'
cask 'dropbox'
cask 'flux'
cask 'font-fira-code'
cask 'font-hack-nerd-font'
cask 'forticlient'
cask 'firefox-developer-edition'
cask 'google-chrome'
#cask 'google-chrome-canary'
#cask 'hammerspoon'
cask 'iterm2'
cask 'kaleidoscope'
cask 'kite'
cask 'kubernetic'
cask 'macdown'
cask 'postman'
cask 'slack'
cask 'sourcetree'
#cask 'sublime-text'
#cask 'the-unarchiver'
cask 'teamsql'
cask 'transmission'
cask 'visual-studio-code'

# Quick Look Plugins (https://github.com/sindresorhus/quick-look-plugins)
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlimagesize'
cask 'webpquicklook'
cask 'suspicious-package'
cask 'qlvideo'
